name: Test

on: 
    push:
        branches:
            - main # To run the script when using the main branch
            - '**' # To run the script for any other branch as well

jobs:
    test: 
        runs-on: macos-latest
        steps:
            - name: Pull the latest code
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x' # works with all python version > 3

            - name: Install pip and pytest
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                  
            - name: Test the cases
              run: | 
                pytest --cov=. --cov-report=term --cov-report=json:coverage.json # to test all cases with code coverage and report to terminal as well as to coverage.json file